### ISSUE TITLE
Strong passwords are not enforced when resetting lost password

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-security#141]
When resetting a lost password through `wp-login.php`, it is possible to use a weak password by ticking the 'Confirm use of weak password' box.

<img width="1077" alt="Screenshot 2021-11-15 at 20 58 37" src="https://user-images.githubusercontent.com/5014023/141853894-500baef5-ef1d-4d3a-a184-6a2b3ba369f6.png">

When resetting through the user's profile, the confirmation box has been removed to enforce a strong password. We should remove the checkbox here too. 

Tested on a fresh local install of V9 (screenshot above) and an existing client project on Altis V8. Screencast available in [Slack](https://hmn.slack.com/archives/C3CKS8LLR/p1637012108087600?thread_ts=1637011993.087500&cid=C3CKS8LLR).

**Comment by roborourke** [comment]
Fixed in #152
