### ISSUE TITLE
Require login and basic auth block robots.txt

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-security#154]
Some non-production sites are being indexed unintentionally, or at least some content is as the require login and basic auth features both block access to robots.txt which is generated by WP.

Acceptance criteria:

- [x] Require login allows unauthenticated access to robots.txt
- [x] Basic auth allows unauthenticated access to robots.txt
- [x] If either require login or basic auth is enabled robots.txt returns:
   ```
   User-agent: *
   Disallow: /
   ```

**Comment by yumito** [comment]
@roborourke estimated at 3 on the last refinement

**Comment by shadyvb** [comment]
@robindevitt all PRs have been merged, let's make sure the changes are reflected in documentation before closing the issue.

**Comment by robindevitt** [comment]
@shadyvb For both `PHP Basic Auth` and `Require login` would the below be appropriate:

>**Note:** Enabling PHP Basic Auth will prevent your site from being indexed with search engines.

>**Note:** Enabling Require Login will prevent your site from being indexed with search engines.

**Comment by mikelittle** [comment]
@robindevitt Is there going to be mention that basic auth doesn't protect your uploads (I think there was mention of an nginx exampleto handle that)
