### ISSUE TITLE
Basic auth cannot be used in production environments

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-security#165]
Steps to reproduce:
1. Set basic auth config up per the instructions in the docs
2. Set an environment override for production
3. View on a production environment

The site should have Basic Auth required, however it does not.

This is due to the merging of the config *always* setting the `php-basic-auth` config rather than using environment overrides correctly, which means it then has environment-specific behaviour. Due to this, you cannot enable it on production per the docs.

I'm filing a hotfix for this which explicitly checks the environment configuration, but we should look at reworking this to be standard instead.

Acceptance criteria:

- [ ] ...

**Comment by shadyvb** [comment]
Merged and backported up to v8. Created https://github.com/humanmade/altis-security/issues/170 to followup.
