### ISSUE TITLE
The 2FA/MFA setup screen is confusing

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-security#200]
When a user gets added or invited to a site which requires multi-factor authentication to be enabled on their account, the initial MFA setup workflow is very confusing. It appears to be optimised for allowing users to use more than one MFA method, but I would expect the most common use case is using one MFA method.

## Screenshot

This is the interstitial MFA configuration screen that a user sees after signing in for the first time. You can trigger this on an account by deleting the `_two_factor_*` user meta fields for a user.

<img width="996" alt="" src="https://user-images.githubusercontent.com/208434/169056182-68a9fee8-51d2-4bb2-8467-b8604207ce1e.png">

## Problems

* If a user wants to use TOTP with Google Authenticator, Authy, 1Password, etc, they have to click three buttons: the "Enabled" checkbox, the "Primary" radio button, and the "View Options" toggle. If they fail to click all three of those then the setup fails.
* There's no client-side checking of the required TOTP code field
* No error message is shown if the user submits the form without having filled out everything they need to.
* There's an unnecessary distinction between enabled and primary on this screen - how many users use multiple MFA methods compared to those who just use one?
* The user is not reminded or forced to generate backup verification codes, greatly increasing the probability of them locking themselves out of their account if they lose access to their MFA method.
* Being able to select "Backup Verification Codes" as the primary or default MFA method makes no sense.
* The empty "Security Keys" listing table at the bottom of the screen makes no sense. This should only be displayed after the user chooses the FIDO option and sets up a new key.
* It should not be possible to set an MFA method as "Primary" without it also being "Enabled".

**Comment by rmccue** [comment]
Thanks for the issue @johnbillion; as this is a wide-ranging set of improvements, not directly a bug, can you file this via the Altis Dashboard roadmap's suggestions instead please? Cheers!
