### ISSUE TITLE
Require secure cookies & HttpOnly

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-security#22]
We could filter the authentication cookies to be set with the secure flag and also to be HTTP Only which prevents accessing the cookies from client side script.

https://www.owasp.org/index.php/HttpOnly

Equivalent PHP ini directives.

```php
ini_set('session.cookie_httponly', true);
ini_set('session.cookie_secure', true);
ini_set('session.use_only_cookies', true);
```

**Comment by rmccue** [comment]
Those ini settings only affect session cookies, and IIRC we don't support sessions?

**Comment by roborourke** [comment]
Yeah realised after I added them, just something I found when I was looking
for more info. We can still edit the cookie though
-- 
Robert O'Rourke
Product Engineer
Human Made Limited <https://humanmade.com/>

<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>

*Get the inside track on enterprise WordPress news in your inbox once a
month
<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>.
Make more informed decisions starting today.*

**Comment by joehoyle** [comment]
The auth cookies are already HttpOnly and Secure:

![](https://joehoyle-captured.s3.amazonaws.com/zfj1Ph0o.png)
