### ISSUE TITLE
Stream plugin does not exist

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-security#24]
After finishing the setup and visiting the admin, I see a notification: `

`The plugin stream/stream.php has been deactivated due to an error: Plugin file does not exist.`

**Comment by joehoyle** [comment]
Yeah that's a good point, we have the composer package, so that's ok. I'm doing to give it a few days to see if there's any interest upstream first.

**Comment by joehoyle** [comment]
Fixed in #23
