### ISSUE TITLE
Add framework for setting script/style integrity hashes

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-security#30]
We should add a framework for Sub-Resource Integrity (SRI). This adds an `integrity` parameter to script/link[rel=style] tags which contains a hash of the resource, allowing sites to avoid being MITM'd as well as CDNs changing assets out on you.

For assets loaded from the filesystem, we can automatically generate integrity hashes and serve these up. We should disable this behaviour for local environments, as it's common to change assets without bumping the version.

For external assets, we can provide an API for registering integrity hashes.

**Comment by rmccue** [comment]
Work underway on https://github.com/humanmade/altis-browser-security/pull/1 - will require the integration piece, as well as copying and adapting the documentation across.

**Comment by roborourke** [comment]
Basic plugin is done but has a few things to figure out still in terms CSPs and some other default headers.

Just need to integrate the browser security plugin with this module.
