### ISSUE TITLE
Warn user more clearly when their password is not accepted

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-security#39]
When a password is not strong enough, the submit button on the profile page is disabled. We need to be clearer about this, as particularly on long profile pages, it may not be obvious why the button is disabled.

Suggested microcopy: "Your password does not meet the minimum requirements. Please select a stronger password."

* [x] When the profile submit button is disabled, display a message warning the user about their password strength next to the button.

*Original description follows*
----

If a user tried to change their password to something considered too weak, they are unable to update their profile. There is no error state to tell them why this is the case. 

![Screenshot 2019-11-19 at 16 53 16](https://user-images.githubusercontent.com/5014023/69167606-25725c00-0aed-11ea-9c7f-e55ab259fef1.png)

With regular WordPress, there is a checkbox that the user must check to confirm the password. This appears and disappears depending on the password strength, drawing the users attention to it.

![Kapture 2019-11-19 at 17 00 23](https://user-images.githubusercontent.com/5014023/69168197-28ba1780-0aee-11ea-8b60-b10025973246.gif)

As this functionality has been removed, we should instead show an additional warning that the password is not accepted.

----------

Acceptance criteria:

- [x] Show a warning message if the password is too weak next to the password field as it is typed

**Comment by rmccue** [comment]
Hmm, there's definitely meant to be an message here:

https://github.com/humanmade/altis-security/blob/460d464c46145a4dab280e3e4f4c66351461afb1/inc/passwords/namespace.php#L114-L116

**Comment by sambulance** [comment]
Ah, the error isn't being shown because the button is disabled unless the password is strong enough. `user_profile_update_errors` fires when the form is submitted, which can't be done if the button is disabled.

**Comment by roborourke** [comment]
Is there anything to do here or can this be closed?

**Comment by sambulance** [comment]
Either don't disable the save button when a weak password is present (this is core behaviour), or show an inline warning by the password box if the password is too weak to use.

**Comment by rmccue** [comment]
I think this is the intended functionality currently, we just need to add an additional warning next to the password field to make it clearer.

**Comment by robindevitt** [comment]
Had a call with @roborourke around the error notice.

> Hmm, there's definitely meant to be an message here:
> 
> https://github.com/humanmade/altis-security/blob/460d464c46145a4dab280e3e4f4c66351461afb1/inc/passwords/namespace.php#L114-L116

This message does display, however it only displays once the form has been submitted. The "Confirm use of weak 
password" checkbox is hidden, it would appear ​we don't want users to have weak passwords on the sites.

The error message will display at the bottom of the edit user screen with an anchor tag link in the message that links the user back to the password section to strengthen their password.

**Comment by robindevitt** [comment]
Issue has been resolved and merged.
