### ISSUE TITLE
require-login cannot be disabled

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-security#48]
The require-login functionality can't be disabled. While the value can be set to `true` in the config, this enables it on all sites. There's no reverse of this to disable the functionality altogether.

**Comment by rmccue** [comment]
We need to determine how we want to handle this.

Should we allow disabling this functionality? If so, should it be a configuration option, or is this an advanced use case (which we could handle with a filter instead)?

At the core of it, the require login functionality essentially exists to "fix" the handing of the `private` field on sites, so does it make sense to disable that?

**Comment by roborourke** [comment]
@rmccue I think this one can be closed now?

**Comment by rmccue** [comment]
Is it fixed? I don't know, is there a PR for fixing it?

**Comment by roborourke** [comment]
My bad, had my wires crossed with some other work we did on the regression in #60 

So you're right, setting the config option to `false` will still load the plugin but respect the site's public setting. Setting it `true` requires login for all sites.

Personally I think this behaviour is fine - it's kind of what you'd expect for a non public site but conversely maybe there are use cases or reasons to support turning it off altogether.

I'd be tempted to wait until that comes up as an issue first though, then we could handle it by allowing string values eg:

- `true|"all"` = require login everywhere
- `false|"none"` = require login nowhere
- `"private"` = require on private sites only

**Comment by jennybeaumont** [comment]
Closing with decision that disabling not be allowed. Can reopen should decision change.
