### ISSUE TITLE
Idea: Web push notification method for recieving 2fa codes

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-security#6]
Wanted to note this idea down while it was fresh in my head.

At the cybersec conference I was at the holy grail for 2FA was to keep everything "in-band" eg. encrypted network traffic between the user and the app only rather than going "out-of-band" via email or sms. Web push / desktop notifications would be the way to achieve this.

Granted not an issue really when using 1pass with the 1 time password field but this method might actually be easier to set up / use for some people and would be an interesting one to explore.

One for down the line.

**Comment by rmccue** [comment]
This is pretty neat, but think this a nice-to-have, so let's close out but keep it in mind if a use case arises.
