### ISSUE TITLE
Add XRay trace ID to audit-log entries

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-security#7]
This is good for tracking which action was caused by what request, if we ever needed to get more data.

**Comment by pdewouters** [comment]
@roborourke I'm not sure where to start with this? Is `audit-log` the Stream plugin? Where do I get the xray data from?

**Comment by joehoyle** [comment]
Ah yes, it is -- we want to add the value of https://github.com/humanmade/aws-xray/blob/master/inc/namespace.php#L281 into each stream log item. This means we can look up a XRay trace from a stream log item.

**Comment by pdewouters** [comment]
Is the idea to add a column to the list table after "IP Address"?

**Comment by joehoyle** [comment]
@pdewouters I don't think it _needs_ to be added in the UI, the most important thing is to get it in the data that is stored in each stream log item, just so in the future if we did need to look up a trace, then we can. I think that's a good start anyway.
