### ISSUE TITLE
Require login breaks all REST API OPTIONS requests even when logged in

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-security#76]
Steps to reproduce:
1. Enabled `require-login` in the Altis config.
2. Send an `http OPTIONS /wp-json/ -H 'Cookie: wordpress_logged_in....` request (psuecode)
3. Observe the response is empty (should be populated with all routes information)

Expected: 

1. Response should be JSON blob of all endpoints
2. `Allow` HTTP header should be present

Acceptance criteria:

- [ ] Logged in requests should have normal REST API OPTIONS behavior

---

The code that is causing this is in https://github.com/humanmade/hm-require-login/blob/master/inc/namespace.php#L21, as you can see, it will shortcircuit all REST API OPTIONS requests regardless of whether the user is logged in.

As far as I can tell, all those REST API exceptions should be placed below the logged in checks at https://github.com/humanmade/hm-require-login/blob/master/inc/namespace.php#L49-L61

**Comment by roborourke** [comment]
I think it just needs to not `exit` at the point where it does so WP can handle the output.
