### ISSUE TITLE
Repeated login attempts do not block users

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-security#79]
`hm-limit-login-attempts` does not appear to be functioning as designed. A support request came in describing being able to attempt a log in more than 5 times. I've been able to reproduce the issue by attempting logging in with bogus credentials on a test environment. Often It simply reset the counter to "3 attempts remaining." Other times it'd say "too many failed login attempts," and on the subsequent request display another counter. Eventually, our nginx configuration kicks in and blocks the repeated attempts.

Steps to reproduce:
1. Attempt to log in with any user more than 4 times.

**Describe what you expected to see:**

User is blocked from an attempted login.

**Screenshots are helpful too if the bug is visual:**

I have one recording that's more in line with my original description, but it had information from 1Password I didnt want to expose. This one is more sanitized, but with less of what I observed:

![limit logins 2020-12-04 12_46_15](https://user-images.githubusercontent.com/314009/101202310-b6e83980-362e-11eb-878b-953b510a5231.gif)

Acceptance criteria:

- [ ] ...

**Comment by jazzsequence** [comment]
At a first pass, I'm not able to reproduce this locally and there doesn't appear to be any observable configuration differences between my local environment and the platform test environment but will doublecheck to make sure my local is completely up-to-date.

**Comment by roborourke** [comment]
This is behaving super inconsistently for me, I've seen it both continue to count down and reset the number of attempts remaining but also eventually locking me out from the plugin side giving me the timer for the cooling off period.

I saw the attempts remaining counting down and resetting when trying repeated logins with a non existent account.

Platform test XRay logs show the correct IP address for my laptop on wifi and my phone on 4G and I'm seeing the "too many attempts" message for the admin user, eventually. It's happening very inconsistently, so maybe there's a cache invalidation problem.
