### ISSUE TITLE
Move Audit Log under tools?

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-security#8]
Audit Log doesn't really need to be a top-level menu; can we move it under either Tools or Settings?

**Comment by joehoyle** [comment]
Yeah that makes sense

**Comment by roborourke** [comment]
I think as it’s network admin only and an important feature it’s good where it is right now. Ok to close this one?

**Comment by roborourke** [comment]
Gonna close for now as network admin doesn't have a tools page.
