### ISSUE TITLE
2FA edit user shows options for current user

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-security#93]
Steps to reproduce:
1. Edit a user other than yourself
2. Update 2FA Enabled option to "email only" (or something other than current setting
3. Hit Update
4. Observe option were not changed

It #turnsout that the currently selected options are _for the current user_, not the user you are editing, so though updating a user will work, you won't see the changes. And if you were to go update that user's name or something, they would be, by default, updated with the current user's options. 

This is happening in https://github.com/humanmade/two-factor/blob/force-2fa/class.two-factor-core.php#L625 `get_available_providers_for_user` takes a `WP_User` object, not an id, and this function falls backs to the current user.

**Comment by rmccue** [comment]
May be fixed upstream, we should see if we need to sync. We should also see if we can eliminate our fork and switch to the regular upstream instead (may not be possible, since force-2fa branch seems to have unmerged changes).

**Comment by roborourke** [comment]
We forked because it's not on packagist, there's been a lot of updates so we should def sync but there's a fair amount of new things that we should just make a patch release for this particular issue. We can roll out the update with v8.
